# Site settings
title: wilko#hack
description: > # this means to ignore newlines until "baseurl:"
  Quant Finance, Home Automation, and general hacks...
baseurl: "/" # the subpath of your site, e.g. /blog/
#url: "cwilko.github.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: rouge
gems: [jekyll-paginate, jekyll-coffeescript, jekyll-seo-tag]

# comments
disqus: cwilko

# author info
# add your appropriate info here
author: Chris Wilkinson
bio: Software Engineer
email: wilkobets@goolemail.com
email_md5: 53a2811e11d37168db6ede33c0334870
twitter_username: chr1swilkinson
github_username: cwilko
logo: http://www.gravatar.com/avatar/53a2811e11d37168db6ede33c0334870?size=75
twitter:
  username: cwilko
social:
  name: Chris Wilkinson
  links:
    - https://twitter.com/chr1swilkinson
    - https://www.linkedin.com/in/chris-wilkinson-a3979234
    - https://github.com/cwilko

# Theming options
# These settings are mandatory.
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
